toeic/urls.py
"""Define URL patterns for toeic"""
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views
urlpatterns = [
	#homepage
	url(r'^$', views.index, name='index'),
	url(r'^vocabs/(?P<vocab_id>\d+)$', views.vocab, name='vocab'),
	url(r'^tests/$', views.tests, name='tests'),
	url(r'^tests/practice$', views.practicetests, name='practicetests'),
	url(r'^tests/(?P<test_id>\d+)/$', views.test, name='test'),
	url(r'^tests/result/(?P<test_id>\d+)/$', views.resulttest, name='resulttest'),
	url(r'^tests/resultvocabtest/(?P<test_id>\d+)/$', views.resultvocabtest, name='resultvocabtest'),
	url(r'^tests/checkvocabtest/(?P<test_id>\d+)/$', views.checkvocabtest, name='checkvocabtest'),
	url(r'^topics/$', views.topics, name='topics'),
	url(r'^topics/searchvocabresult/(?P<word>[\w\-]+)/$', views.searchvocabresult, name='searchvocabresult'),
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	url(r'^topics/checkvocab/(?P<topic_id>\d+)/$', views.checkvocab, name='checkvocab'),
	url(r'^topics/resultvocab/(?P<topic_id>\d+)/(?P<session>\d+)/$', views.resultvocab, name='resultvocab'),
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^grammartopics/$', views.grammartopics, name='grammartopics'),
	url(r'^grammartopics/(?P<grammartopic_id>\d+)/$', views.grammartopic, name='grammartopic'),
	url(r'^grammartopics/quiz/(?P<grammartopic_id>\d+)/$', views.grammartopicquiz, name='grammartopicquiz'),
	url(r'^grammartopics/resultquiz/(?P<grammartopic_id>\d+)/$', views.resultgrammartopicquiz, name='resultgrammartopicquiz'),
	url(r'^videos/part3/$', views.toeicpart3videos, name='toeicpart3videos'),
	url(r'^videos/part3/(?P<video_id>\d+)/$', views.toeicpart3video, name='toeicpart3video'),
	url(r'^videos/result/(?P<video_id>\d+)/$', views.resulttoeicvideo, name='resuttoeicvideo'),
	url(r'^videos/dictation/(?P<video_id>\d+)/$', views.dictation, name='dictation'),
	url(r'^videos/dictation/result/(?P<video_id>\d+)/$', views.resultdictation, name='resultdictation'),
	url(r'^pronunciation/lessons/$', views.pronunciationlessons, name='pronunciationlessons'),
	url(r'^pronunciation/lessons/(?P<pronunciationlesson_id>\d+)/$', views.pronunciationlesson, name='pronunciationlesson'),
	#url(r'^pronunciation/dictation/(?P<pronunciationlesson_id>\d+)/$', views.pronunciationdictation, name='pronunciationdictation'),
	#url(r'^pronunciation/dictation/result/(?P<pronunciationlesson_id>\d+)/$', views.pronunciationresultdictation, name='pronunciationdictation'),
	url(r'^speaking/topics/$', views.speakingtopics, name='speakingtopics'),
	url(r'^speaking/topics/(?P<speakingtopic_id>\d+)/$', views.speakingtopic, name='speakingtopic'),
	url(r'^speaking/topics/(?P<speakingtopic_id>\d+)/(?P<speakinglesson_id>\d+)/$', views.speakinglesson, name='speakinglesson'),
	url(r'^speaking/topics/(?P<speakingtopic_id>\d+)/(?P<speakinglesson_id>\d+)/(?P<remain>\d+)/$', views.speakingpractice, name='speakingpractice'),
	]

toeiclily/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^music/', include(music.urls)),
    url(r'', include('toeic.urls', namespace = 'toeic')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

toeic/views.py
# Create your views here.
import operator
from collections import OrderedDict
from django.shortcuts import render
from .models import Topic, Test, Question, Answer, Vocab, UserVocab, UserAnswer, GrammarTopic, UserAnswerGrammarQuiz, UserAnswerVideoLesson, UserDictation, VideoLesson, Dictation, PronunciationLesson, SpeakingAnswer, SpeakingQuestion, SpeakingTopic, SpeakingLesson, SpeakingPractice
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from .form import UserVocabForm, UserDictationForm, UserAnswerForm, UserAnswerGrammarQuizForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
    """The home page for toeic"""
    return render(request, 'toeic/index.html')

def vocab(request,vocab_id):
    """Show 1 word"""
    vocab = Vocab.objects.get(id=vocab_id)
    question = vocab.question_set.all().first()
    context = {'vocab': vocab, 'question': question}

    return render(request, 'toeic/vocab.html', context)

def tests(request):
    """Show all tests"""
    tests = Test.objects.filter(testType=1).order_by('date_added')
    context = {'tests': tests}
    return render(request, 'toeic/tests.html', context)

def practicetests(request):
    """Show all practicetests"""
    practicetests = Test.objects.filter(testType=2).order_by('date_added')
    context = {'tests': practicetests}
    return render(request, 'toeic/practicetests.html', context)

def topics(request):
    """Show all topics"""
    if request.method != 'POST':
        form = SearchForm()
    else:
        form = SearchForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data['text']
            return HttpResponseRedirect(reverse('toeic:searchvocabresult', args=[word]))

    topics = Topic.objects.order_by('text')
    context = {'topics':topics, 'form':form}

    return render(request, 'toeic/topics.html', context)

def searchvocabresult(request, word):
    vocabs = Vocab.objects.filter(text__icontains=word)
    vocabsdict = OrderedDict()
    for vocab in vocabs:
        question = vocab.question_set.all().first()
        vocabsdict[vocab] = question

    context = {'vocabs':vocabsdict}
    return render(request, 'toeic/searchvocabresult.html', context)

def topic(request, topic_id):
    """show a single topic and all its vocabs"""
    topic = Topic.objects.get(id=topic_id)
    vocabs = topic.vocab_set.all()
    vocabsdict = OrderedDict()
    for vocab in vocabs:
        question = vocab.question_set.all().first()
        vocabsdict[vocab] = question
    context = {'topic': topic, 'vocabs':vocabsdict}
    return render(request, 'toeic/topic.html', context)

def checkvocab(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    vocabs = topic.vocab_set.all()
    vocabs_dict = {}
    if request.user.is_authenticated():
            currentUser = request.user
    else:
        return HttpResponseRedirect(reverse('toeic:index'))

    if request.method != 'POST':
        for vocab in vocabs:
            form = UserVocabForm(prefix=vocab.id)
            vocabs_dict[vocab] = form
    else:
        try:
            lastanswer = UserVocab.objects.filter(user = currentUser.id).latest("date_added")
            session = lastanswer.session + 1
        except UserVocab.DoesNotExist:
            session = 1

        for vocab in vocabs:
            form = UserVocabForm(request.POST, prefix=vocab.id)
            if form.is_valid():
                new_uservocab = UserVocab()
                new_uservocab.session = session
                new_uservocab.user = currentUser
                new_uservocab.vocab = vocab
                new_uservocab.text = form.cleaned_data['text']
                new_uservocab.save(force_insert=True)
            vocabs_dict[vocab] = form

        return HttpResponseRedirect(reverse('toeic:resultvocab', kwargs={'topic_id':topic.id,'session': session}))

    context = {'topic': topic, 'vocabs':vocabs_dict}
    return render(request, 'toeic/checkvocab.html', context)

def resultvocab(request, topic_id, session):
    topic = Topic.objects.get(id=topic_id)
    vocabs = topic.vocab_set.all()
    vocabs_dict = {}
    if request.user.is_authenticated():
        currentUser = request.user
    else:
        return HttpResponseRedirect(reverse('toeic:index'))

    try:
        # lastanswer = UserVocab.objects.filter(user = currentUser.id).latest("date_added")
        # session = lastanswer.session
        user_uservocabs = UserVocab.objects.filter(user = currentUser.id).filter(session = session)
        for vocab in vocabs:
            # if UserVocab.objects.filter(user = currentUser.id).filter(session = session).filter(vocab = vocab.id).exists():
            #     user_uservocab = UserVocab.objects.filter(user = currentUser.id).filter(session = session).filter(vocab = vocab.id).latest("date_added")
            #     user_vocab = user_uservocab.text
            isanswer = False
            for user_uservocab in user_uservocabs:
                if user_uservocab.vocab == vocab:
                    user_vocab = user_uservocab.text
                    isanswer = True
            if isanswer == False:
                user_vocab = "Unknown"
            vocabs_dict[vocab] = user_vocab
    except UserVocab.DoesNotExist:
        for vocab in vocabs:
            user_vocab = "Unknown"
            vocabs_dict[vocab] = user_vocab

    context = {'topic': topic, 'vocabs':vocabs_dict}
    return render(request, 'toeic/resultvocab.html', context)

def checkvocabtest(request, test_id):
    test = Test.objects.get(id=test_id)
    questions = test.question_set.all()
    vocabs_list = []

    for question in questions:
        vocabs = question.vocabs.all()
        for vocab in vocabs:
            vocabs_list.append(vocab)

    vocabs_dict = {}

    if request.user.is_authenticated():
            currentUser = request.user
    else:
        return HttpResponseRedirect(reverse('toeic:index'))

    if request.method != 'POST':
        for vocab in vocabs_list:
            form = UserVocabForm(prefix=vocab.id)
            vocabs_dict[vocab] = form
    else:
        try:
            lastanswer = UserVocab.objects.filter(user = currentUser.id).latest("date_added")
            session = lastanswer.session + 1
        except UserVocab.DoesNotExist:
            session = 1

        for vocab in vocabs_list:
            form = UserVocabForm(request.POST, prefix=vocab.id)
            if form.is_valid():
                new_uservocab = UserVocab()
                new_uservocab.session = session
                new_uservocab.typeOfTest = 2
                new_uservocab.user = currentUser
                new_uservocab.vocab = vocab
                new_uservocab.text = form.cleaned_data['text']
                new_uservocab.save(force_insert=True)
            vocabs_dict[vocab] = form
        return HttpResponseRedirect(reverse('toeic:resultvocabtest', args=[test.id]))

    context = {'test': test, 'vocabs':vocabs_dict}
    return render(request, 'toeic/checkvocabtest.html', context)

def resultvocabtest(request, test_id):
    if request.user.is_authenticated():
        currentUser = request.user
    else:
        return HttpResponseRedirect(reverse('toeic:index'))

    test = Test.objects.get(id=test_id)
    questions = test.question_set.all()
    vocabs_list = []
    for question in questions:
        vocabs = question.vocabs.all()
        for vocab in vocabs:
            vocabs_list.append(vocab)

    vocabs_dict = {}

    try:
        lastanswer = UserVocab.objects.filter(user = currentUser.id).latest("date_added")
        session = lastanswer.session

        for vocab in vocabs:
            if UserVocab.objects.filter(user = currentUser.id).filter(session = session).filter(vocab = vocab.id).exists():
                user_uservocab = UserVocab.objects.filter(user = currentUser.id).filter(session = session).filter(vocab = vocab.id).latest("date_added")
                user_vocab = user_uservocab.text
            else:
                user_vocab = "Unknown"
            vocabs_dict[vocab] = user_vocab
    except UserVocab.DoesNotExist:
        for vocab in vocabs:
            user_vocab = "Unknown"
            vocabs_dict[vocab] = user_vocab

    context = {'test': test, 'vocabs':vocabs_dict}
    return render(request, 'toeic/resultvocabtest.html', context)

def test(request, test_id):
    test = Test.objects.get(id=test_id)
    questions = test.question_set.all()
    questions_dict = OrderedDict()
    if request.user.is_authenticated():
        currentUser = request.user
    else:
        return HttpResponseRedirect(reverse('toeic:index'))

    if request.method != 'POST':
        for question in questions:
            form = UserAnswerForm(question.id, prefix=question.id)
            questions_dict[question] = form
    else:
        try:
            lastanswer = UserAnswer.objects.filter(user = currentUser.id).latest("date_added")
            session = lastanswer.session + 1
        except UserAnswer.DoesNotExist:
            session = 1

        for question in questions:
            form = UserAnswerForm(question.id, request.POST, prefix=question.id)
            question_id = question.id
            if form.is_valid():
                new_useranswer = UserAnswer()
                new_useranswer.session = session
                new_useranswer.user = currentUser
                new_useranswer.question = question
                new_useranswer.test = test
                new_useranswer.answer = form.cleaned_data['answer']
                new_useranswer.save(force_insert=True)

                request.session[question_id] = form.cleaned_data['answer']
            else:
                request.session[question_id] = 'unknown'
        return HttpResponseRedirect(reverse('toeic:resulttest', args=[test.id]))

toeic/templates/toeic/checkvocab.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:topics' %}">Topic</a>:
                <strong>{{topic}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <form method="Post"/>
			<table class="table">
				{% for vocab, form in vocabs.iteritems %}
					<tr>
						<td style ="padding-left: 120px">{{ vocab.text}}</td>
						<td style ="padding-left: 120px">{% csrf_token %} {{ form.text }} </td>
					</tr>
				{% empty %}
					<tr>No words have been added yet.</tr>
				{% endfor %}
			</table>
			<div class ="text-center"><button class="btn btn-danger" name="submit">Submit</button></div>
			</form>
        </div>
   </div>
</div>
</div>
{% endblock content %}

toeic/templates/toeic/grammartopic.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:grammartopics'%}">Grammar Topic</a>:
                <strong>{{grammartopic}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <p id="grammartopic">{{ grammartopic.text|safe }}</p>
            <div class ="text-center"><button type="button" class="btn btn-info"><a href="{% url 'toeic:grammartopicquiz' grammartopic.id %}">Take a quiz?</a></button></div>
        </div>
   </div>
</div>
</div>
{% endblock content %}

toeic/templates/toeic/practicetests.html
{% extends "toeic/base.html" %}

{% block content %}

<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Practice Exercises</strong>
            </h2>
            <hr>
    	</div>
    	<div class="col-lg-12">
            <div class="list-type5">
				<ol>
				{% for test in tests %}
					<li>
					<a href="{% url 'toeic:test' test.id %}">{{ test }}</a>
					</li>
				{% empty %}
					<li>No tests have been added yet.</li>
				{% endfor %}
				 </ol>
			</div>
    	</div>
    </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/resulttest.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:tests' %}">Test</a>:
                <strong>{{test}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
			<table class="table">
				{% for question, list in questions.iteritems %}
					<tr>
						<td style ="">
						{{ question.text|linebreaks }}
						{% if question.explanation %}
						<p><strong>Explanation</strong></br> <span style="font-style: italic; font-size: 1em">{{question.explanation}}</span></p>
						{% endif%}
						<p><strong>Translation</strong></br> <span style="font-style: italic; font-size: 1em">{{question.translation}}</p>
						{% if list.2 %}
						<p class="grammartopiclink"><strong>Grammar Topics related</strong></br>
						{%for grammartopic in list.2 %}
						<a style="font-size:1em; color:blue" href ="{% url 'toeic:grammartopic' grammartopic.id %}" target="_blank">{{grammartopic}}</a></br>
						{% endfor %}
						</p>
						{% endif %}
						{% if question.audio %}
						<div>
						    <audio controls>
						    <source src="{{ question.audio.url }}" type="audio/wav">
                            Your browser does not support the audio element.
                            </audio>
                        </div>
                        {% endif %}
                        {% if list.4 %}
						    <a id="vocab-{{question.id}}" style="cursor: pointer;"><strong>Vocab</strong></br></a>
						    <div id="vocabs-{{question.id}}" style="display:none;">
						    {%for vocab in list.4 %}
						    <a href="{% url 'toeic:vocab' vocab.id %}"><span style="color:green">{{vocab}}</span> : {{vocab.definition}}</a><br>
						    {% endfor %}
						    </div>
						    <script>
                            $( "#vocab-{{question.id}}" ).click(function() {
                            $( "#vocabs-{{question.id}}" ).toggle(function() {
                            });
                            });
                            </script>
                        {% endif %}
                            <br>
						</td>
						<td style ="">
						{%for answer in list.0 %}
						{% if answer.istrue != False %}
		                    <p style="color:green;">{{answer.text}}</p>
						{% else %}
							<p>{{answer.text}}</p>
						{% endif %}
						{% endfor %}
						</td>
						<td>
						{% if list.3 == False %}
							<p style="color:red;">{{list.1}}</p>
						{% else %}
							<p>{{list.1}}</p>
						{% endif %}
						</td>
					</tr>
					{% empty %}
					<tr>No questions have been added yet.</tr>
					{% endfor %}
			</table>
			<div class ="text-center" style="margin:10px"><p>Number of correct answers:{{rightanswers}}</p></div>
			<div class ="text-center"><button class="btn btn-info"><a href="{% url 'toeic:checkvocabtest' test.id %}">Check your vocabulary</button></div>
        </div>
   </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/resultvideo.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:toeicpart3videos' %}">Conversation</a>:
                <strong>{{video}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <div class ="text-center">
            <iframe width="853" height="480" src="{{video.url}}" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="col-lg-12">
			<table class="table">
				{% for question, list in questions.iteritems %}
					<tr>
					    <td>
						<div>
						{{ question.text|linebreaks }}
						{% if question.explanation %}
						<p><strong>Explanation:</strong></br> <span style="font-style: italic; font-size: 1em">{{question.explanation}}</span></p>
						{% endif%}
						</div>
						<div style ="">
						    <ul>
						        {%for answer in list.0 %}
        						{% if answer.istrue != False %}
        		                    <li style="color:green;">{{answer.text}}</li>
        						{% else %}
        							<li>{{answer.text}}</li>
        						{% endif %}
        						{% endfor %}
						    </ul>
						</div>
						</td>
						<td>
						{% if list.2 == False %}
							<p style="color:red;">{{list.1}}</p>
						{% else %}
							<p>{{list.1}}</p>
						{% endif %}
						</td>
					</tr>
					{% empty %}
					<tr>No questions have been added yet.</tr>
					{% endfor %}
			</table>
        <div class="col-lg-12">
            <table class="table">
				{% for vocab in vocabs %}
					<tr>
						<td style ="padding-left: 20px"><a href="{% url 'toeic:vocab' vocab.id %}">{{ vocab.text}}</a></td>
						<td style ="font-size: 0.8em;">{{vocab.wordType}}</td>
						<td style ="padding-left: 20px">{{ vocab.definition }}</td>
						{% if vocab.audio %}
						<td style ="padding-left: 20px">
						    <audio controls>
						    <source src="{{ vocab.audio.url }}" type="audio/wav">
                            Your browser does not support the audio element.
                            </audio>
                        </td>
                        {% endif %}
					</tr>
				{% empty %}
					<tr>No words have been added yet.</tr>
				{% endfor %}
			</table>
			<div class ="text-center"><button type="button" class="btn btn-info"><a href="{% url 'toeic:dictation' video.id %}">Practice your listening skills</a></button></div>
        </div>
   </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/resultvocab.html
{% extends "toeic/base.html" %}

{% block content %}

<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:topics' %}">Topic</a>:
                <strong>{{topic}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <table class="table">
				{% for vocab, user_vocab in vocabs.iteritems %}
					<tr>
						<td style ="padding-left: 80px">{{ vocab.text}}</td>
						<td style ="font-size: 0.8em;">{{vocab.wordType}}</td>
						<td style ="padding-left: 80px">{{ vocab.definition }}</td>
						<td style ="padding-left: 50px; color:red">{{ user_vocab }}</td>
					</tr>
				{% empty %}
					<tr>No words have been added yet.</tr>
				{% endfor %}
			</table>
			<div class ="text-center"><button type="button" class="btn btn-info"><a href="{% url 'toeic:checkvocab' topic.id %}">Take quiz again?</a></button></div>
        </div>
   </div>
</div>
</div>


{% endblock content %}

toeic/templates/toeic/speakingtopic.html
{% extends "toeic/secondbase.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:speakingtopics' %}">Topic</a>:
                <strong>{{speakingtopic}}</strong>
            </h2>
            <hr>
    	</div>
    	<div class="col-lg-12">
            <div class="list-type5">
				<ol>
				{% for speakinglesson in speakinglessons %}
					<li>
					<a href="{% url 'toeic:speakinglesson' speakingtopic.id speakinglesson.id %}">{{ speakinglesson }}</a>
					</li>
				{% empty %}
					<li>No lessons have been added yet.</li>
				{% endfor %}
				 </ol>
			</div>
    	</div>
    </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/test.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:tests' %}">Test</a>:
                <strong>{{test}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <form method="Post"/>
			<table class="table">
				{% for question, form in questions.iteritems %}
					<tr>
						<div>{{ question.text|linebreaks }}</div>
						<div>{% csrf_token %} {{ form.answer }}</div>
					</tr>
				{% empty %}
					<tr>No questions have been added yet.</tr>
				{% endfor %}
			</table>
			<div class ="text-center"><button class="btn btn-danger" name="submit">Submit</button></div>
			</form>
        </div>
   </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/tests.html
{% extends "toeic/base.html" %}

{% block content %}
 
<div class ="container">
<div class="row">
    <div class="box">  
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Tests</strong>
            </h2>
            <hr>
    	</div>
    	<div class="col-lg-12">
            <div class="list-type5">
				<ol> 
				{% for test in tests %}
					<li>
					<a href="{% url 'toeic:test' test.id %}">{{ test }}</a>
					</li> 
				{% empty %} 
					<li>No tests have been added yet.</li> 
				{% endfor %} 
				 </ol> 
			</div>
    	</div>
    </div>
</div>
</div>

{% endblock content %}


toeic/templates/toeic/topics.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Topics</strong>
            </h2>
            <hr>
    	</div>
    	<div class="col-lg-12">
    	    <div class ="text-center">
    	    <form method="Post"/>
    	    {% csrf_token %} {{ form.text }}
    	    <button class="btn btn-info" name="submit">Search</button>
    	    </form>
    	    </div>
    	</div>
    	<div class="col-lg-12">
            <div class="list-type5">
				<ol>
				{% for topic in topics %}
					<li>
					<a href="{% url 'toeic:topic' topic.id %}">{{ topic }}</a>
					</li>
				{% empty %}
					<li>No topics have been added yet.</li>
				{% endfor %}
				 </ol>
			</div>
    	</div>
    </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/video.html
{% extends "toeic/base.html" %}

{% block content %}
<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><a href="{% url 'toeic:toeicpart3videos' %}">Conversation</a>:
                <strong>{{video}}</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12">
            <div class ="text-center">
            <iframe width="853" height="480" src="{{video.url}}" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="col-lg-12" style="margin: 20px">
            <form method="Post"/>
			<table class="table">
				{% for question, form in questions.iteritems %}
					<tr>
						<div><p>{{ question.text|linebreaks }}</p></div>
						<div><p>{% csrf_token %} {{ form.answer }}</p></div>
					</tr>
				{% empty %}
					<tr>No questions have been added yet.</tr>
				{% endfor %}
			</table>
			<div class ="text-center"><button class="btn btn-danger" name="submit">Submit</button></div>
			</form>
        </div>
        <!--<div class="col-lg-12">
            <table class="table">
				{% for vocab in vocabs %}
					<tr>
						<td style ="padding-left: 20px">{{ vocab.text}}</td>
						<td style ="font-size: 0.8em;">{{vocab.wordType}}</td>
						<td style ="padding-left: 20px">{{ vocab.definition }}</td>
						{% if vocab.audio %}
						<td style ="padding-left: 20px">
						    <audio controls>
						    <source src="{{ vocab.audio.url }}" type="audio/wav">
                            Your browser does not support the audio element.
                            </audio></td>
                        {% endif %}
					</tr>
				{% empty %}
					<tr>No words have been added yet.</tr>
				{% endfor %}
			</table>
        </div>-->
   </div>
</div>
</div>

{% endblock content %}

toeic/templates/toeic/videos.html
{% extends "toeic/base.html" %}

{% block content %}

<div class ="container">
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                <strong>Videos</strong>
            </h2>
            <hr>
    	</div>
    	<div class="col-lg-12">
            <div class="list-type5">
				<ol>
				{% for video in videos %}
					<li>
					<a href="{% url 'toeic:toeicpart3video' video.id %}">{{ video }}</a>
					</li>
				{% empty %}
					<li>No videos have been added yet.</li>
				{% endfor %}
				 </ol>
			</div>
    	</div>
    </div>
</div>
</div>

{% endblock content %}